name: Tests

on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v4

        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '8.2'
                tools: composer:v2

        -   name: Install dependencies
            run: composer install --prefer-dist --no-progress

        -   name: Unit tests with coverage
            run: composer test:unit:co

        -   name: Type coverage
            run: composer test:type-co

        -   name: PHPStan
            run: composer test:stan

        -   name: Test PHP formating
            run: composer test:format:php